---
title: "main_project.Rmd"
author: "Joey Ferkull"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message = FALSE}

library(tidyverse)
#install.packages("tidytext")
library(tidytext) # for getting freq of words

```

```{r load_dataset}

ow <- readr::read_csv("neiss2020.csv")

```

```{r subsetting_data}

bow <- ow %>% 
  subset(Age > 200)
aow <- ow %>% 
  subset(Age <200 & Age > 17)
kow <- ow %>%
  subset(Age <18 & Age > 1)

```

```{r getting only product and narrative together}

prod_narr <- bow %>% 
  mutate( Product = Product_1, Narrative = Narrative_1) %>% 
  select(c(Product,Narrative)) %>%
  arrange(Product)

```


```{r getting variable code descriptions from pdf}
#install.packages("Rcpp")
library(Rcpp)
#install.packages("pdftools")
library(pdftools)


download.file("https://www.cpsc.gov/s3fs-public/2019_NEISS_Coding_Manual.pdf", "product_codes.pdf", mode = "w")

product_data <- pdf_data("product_codes.pdf")
text_analysis <- as.data.frame(product_data[175])

text_values <- text_analysis %>% 
  select(-c("width", "height", "x", "y", "space")) %>%
  slice(21:233) %>% 
  pull(text)

#str_split(text_values, "...[:digit:]" )

unlist(str_split(text_values, " ,"))

product_list <- split(text_values, cumsum(str_detect(text_values, "[:digit:]")))

#codes <- as.data.frame(product_list)
```


```{r creating age in months}

bow <- bow %>% 
  mutate( Age_in_Months = Age - 200) %>% 
  select(-c("Age", "Other_Race","Other_Diagnosis", "Other_Diagnosis_2", "Stratum", "PSU", "Weight" ))


```

```{r viewing counts}
#install.packages("modelsummary")
#library(modelsummary)

#cross-tabs for variables
#datasummary_crosstab(Alcohol ~ Body_Part * Diagnosis, output = "alcohol.html",data = bow)
#the crosstabs did not work as expected so I won't use it

#group by product used
bow %>% 
  group_by(Product_1) %>% 
  summarise(n=n()) %>% 
  arrange(desc(n))

#group by body part
bow %>% 
  group_by(Body_Part) %>% 
  summarise(n=n()) %>% 
  arrange(desc(n))

#group by diagnosis
bow %>% 
  group_by(Diagnosis) %>% 
  summarise(n=n()) %>% 
  arrange(desc(n))


```

```{r dealing with top 10 products}

bow <- bow %>% 
  mutate(Product_1 = case_when(
    Product_1 == 4076 ~ "beds or bedframes",
    Product_1 == 1807 ~ "floors or flooring materials",
    Product_1 == 1842 ~ "stairs or steps",
    Product_1 == 679 ~ "couches",
    Product_1 == 4057 ~ "tables",
    Product_1 == 4074 ~ "chairs",
    Product_1 == 1893 ~ "doors",
    Product_1 == 1395 ~ "toys",
    Product_1 == 611 ~ "bathtubs",
    Product_1 == 1931 ~ "tablet or capsule drugs",
    TRUE ~ as.character(Product_1)
  ))

bow %>% 
  group_by(Product_1) %>% 
  summarise(n=n()) %>% 
  arrange(desc(n)) %>% 
  slice_head(n=10) %>% 
  ggplot(aes(x= Product_1, y=n))+
  geom_col() + coord_flip()

```



```{r breaking down Treatment_Date variable}

bow <- bow %>% 
  separate(Treatment_Date, into = c("Month", "Day", "Year"),"/") %>% 
  select( -("Year"))
  
bow <- bow %>% 
  mutate(Day = case_when(
    Day == 5 | Day == 12 | Day == 19 | Day == 26 ~ "Sunday",
    Day == 6 | Day == 13 | Day == 20 | Day == 27 ~ "Monday",
    Day == 7 | Day == 14 | Day == 21 | Day == 28 ~ "Tuesday",
    Day == 1 | Day == 8  | Day == 15 | Day == 22 | Day == 29 ~ "Wednesday",
    Day == 2 | Day == 9  | Day == 16 | Day == 23 | Day == 30 ~ "Thursday",
    Day == 3 | Day == 10 | Day == 17 | Day == 24 | Day == 31 ~ "Friday", TRUE ~ "Saturday"
  ))
#counting number of cases per month
bow %>% 
  group_by(Day, Month) %>% 
  summarise(day_count = n()) %>% 
ggplot(aes(x = Month, y = day_count)) +
  geom_col(state = "identity")

#trying to get lollipop graph
bow <- bow %>% 
  mutate(Month = case_when(
    Month == 1 ~ "January", Month == 2 ~ "February", Month == 3 ~ "March", Month == 4 ~ "April", Month == 5 ~ "May", Month == 6 ~ "June", Month == 7 ~ "July", Month == 8 ~ "August", Month == 9 ~ "September", Month == 10 ~ "October", Month == 11 ~ "November", TRUE ~ "December"
  ))
  
bow %>% 
  group_by(Month) %>% 
  summarise(day_count = n()) %>% 
  arrange(day_count) %>% 
  mutate(Month = factor(Month, Month)) %>% 
  ggplot(aes(x=Month, y=day_count)) +
  geom_point() + 
  geom_segment( aes(x=Month, xend=Month, y=0, yend=day_count))+
    coord_flip()

#counting number of cases per day of week
#W,R, & F had 4 days, the rest had 3
bow %>% 
  ggplot(aes(x = Day)) +
  geom_bar()

```


```{r breaking down Narrative_1 variable}

Narrative <- bow %>% 
  pull(Narrative_1)
Narrative <- tibble(Narrative)

filt_nar <- Narrative %>% 
  unnest_tokens(word, Narrative) %>% 
  anti_join(tidytext::stop_words) %>% 
  count(word, sort=TRUE)

extra_words = c("dx","pt","mom", "mof", "chi", "lac", "fx", "loc", "rt")

filt_nar <- filt_nar %>% 
  filter(!word %in% extra_words)

```

```{r assembling wordcloud}

require(devtools)
#install_github("lchiffon/wordcloud2")
library(wordcloud2)

png("wordcloud.png")
wordcloud2(filt_nar,
           color = "red",
           backgroundColor = "gray")
dev.off()

```

```{r trying chisq test for alcohol, drugs, and fire}
#install.packages("chisq.posthoc.test")
library(chisq.posthoc.test)

alc <- ow %>% 
  mutate(Fire_Involvement = case_when(
    Fire_Involvement == 0 ~ "No", TRUE ~ "Yes"
  ),
  Alcohol = case_when(
    Alcohol == 0 ~ "No", TRUE ~ "Yes"
  ),
  Drug = case_when(
    Drug == 0 ~ "No", TRUE ~ "Yes"
  ),
  Disposition = case_when(
    Disposition == 1 ~ "Treated & Released", Disposition == 2 ~ "Treated & Transferred", Disposition == 4 ~ "Treated & Hospitalized", Disposition == 5 ~ "Held for Observation",
    Disposition == 6 ~ "Left Without Being Seen", Disposition == 8 ~ "Fatality",
    TRUE ~ "Unknown"
  )) %>% 
  mutate(Fire = Fire_Involvement) %>% 
  select(c(Fire, Alcohol, Drug, Disposition))

#chisq test
M <- table(alc$Fire, alc$Alcohol)
M
chisq.test(alc$Fire, alc$Alcohol, correct = FALSE)
#post hoc
chisq.posthoc.test(M, method = "bonferroni")


#Chi sq test
Q <- table(alc$Fire, alc$Disposition)
Q
chisq.test(alc$Fire, alc$Disposition, correct = FALSE)
#post hoc
chisq.posthoc.test(Q, method = "bonferroni")

```

